export const SET_METCASTS = 'SET_METCASTS'
export const GET_METCASTS = 'GET_METCASTS'
export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const LOGIN_USER = 'LOGIN_USER'
export const REGISTER_USER = 'REGISTER_USER'
export const SET_USER = 'SET_USER'
export const SHOW_LOGIN_FORM = 'SHOW_LOGIN_FORM'
export const SIGN_OUT = 'SIGN_OUT'
